
import React,{useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000/api";
const meta={MEMBER:["عضو","◉"],ADMIN:["ADMIN","◆"],BROKER:["وسيط","▣"],OWNER:["OWNER","♛"],OWNER_ASSISTANT:["مساعد Owner","◇"]};
function App(){const[u,setU]=useState(JSON.parse(localStorage.getItem("sa_user")||"null"));const[t,setT]=useState(localStorage.getItem("sa_token"));const[type,setType]=useState("MEMBER");const[p,setP]=useState("home");const[dark,setDark]=useState(false);
async function login(){const id=prompt("للتجربة المحلية فقط — أدخل Telegram ID:","123456789");if(!id)return;try{const r=await fetch(API+"/auth/telegram",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({telegramId:id,telegramUsername:"demo_user",telegramName:"Super Amazon User",accountType:type})});const d=await r.json();if(!r.ok)throw Error(d.message);localStorage.setItem("sa_token",d.token);localStorage.setItem("sa_user",JSON.stringify(d.user));setT(d.token);setU(d.user)}catch(e){alert(e.message)}}function logout(){localStorage.clear();setT(null);setU(null)}
if(!t)return <Login type={type} setType={setType} login={login}/>;
const role=u.role==="OWNER"||u.role==="OWNER_ASSISTANT"?u.role:u.account_type;return <div className={dark?"shell dark":"shell"}><Side role={role} page={p} setPage={setP} logout={logout}/><main><header><div><small>Super Amazon / لوحة التحكم</small><h1>مرحبًا، {u.telegram_name||"بك"} 👋</h1></div><div><button className="icon" onClick={()=>setDark(!dark)}>☾</button><span className="user">{meta[role]?.[0]}</span></div></header><Router role={role} page={p} user={u} setPage={setP}/></main></div>}
function Login({type,setType,login}){return <div className="login"><section className="brand"><b>SA</b><small>PLATFORM • 2026</small><h1>SUPER<br/><span>AMAZON</span></h1><p>منصة موحدة للأعضاء والـ ADMIN والوسطاء بإدارة Owner مركزية وآمنة.</p><p>◈ هوية Telegram</p><p>◈ طلبات تحقق ومراجعة</p><p>◈ مالية وشكاوى وإشعارات</p></section><section className="loginbox"><small>● بوابة الدخول</small><h2>ابدأ من Telegram</h2><p>اختر نوع الحساب الذي تريد التقديم عليه.</p><div className="roles">{["MEMBER","ADMIN","BROKER"].map(x=><button className={type===x?"sel":""} onClick={()=>setType(x)}><b>{meta[x][1]} {meta[x][0]}</b><small>{x==="MEMBER"?"دخول مباشر":"يحتاج طلب ومراجعة"}</small></button>)}</div><button className="telegram" onClick={login}>➤ تسجيل الدخول عبر Telegram</button><small>وضع الاختبار المحلي مفعل حاليًا.</small><footer>المطور <a href="https://t.me/R_M_D" target="_blank">@R_M_D</a></footer></section></div>}
function Side({role,page,setPage,logout}){let items=[["home","الرئيسية","⌂"]];if(role==="MEMBER")items.push(["complaints","الشكاوى","⚑"]);if(role==="ADMIN")items.push(["application","حالة الطلب","▣"]);if(role==="BROKER")items.push(["finance","المالية","₿"],["payments","الدفعات","↗"],["receipts","الإيصالات","▧"]);if(role==="OWNER"||role==="OWNER_ASSISTANT")items.push(["users","المستخدمون","♟"],["requests","الطلبات","✓"],["complaints","الشكاوى","⚑"],["finance","مالية الوسطاء","₿"],["reports","التقارير","▥"],["assistants","المساعدون والصلاحيات","◇"],["audit","سجل العمليات","◌"],["backup","النسخ الاحتياطي","↻"],["system","حالة النظام","▦"]);items.push(["notifications","الإشعارات","◉"],["rules","القوانين والتوجيهات","▤"],["profile","ملفي الشخصي","◎"],["settings","الإعدادات","⚙"]);return <aside><div className="logo"><b>SA</b><span>SUPER AMAZON<small>CONTROL PLATFORM</small></span></div>{items.map(x=><button className={page===x[0]?"nav active":"nav"} onClick={()=>setPage(x[0])}>{x[2]}<span>{x[1]}</span></button>)}<div className="bottom"><a href="https://t.me/R_M_D" target="_blank">↗ تواصل مع المطور<br/><small>@R_M_D</small></a><button onClick={logout}>⇦ تسجيل الخروج</button></div></aside>}
function Router({role,page,user,setPage}){if(page==="home")return <Home role={role} user={user} setPage={setPage}/>;if(page==="complaints")return <Complaints/>;if(page==="finance")return <Finance/>;if(page==="payments")return <Basic title="الدفعات" icon="↗"/>;if(page==="receipts")return <Basic title="الإيصالات" icon="▧"/>;if(page==="application")return <Basic title="حالة الطلب" icon="▣"/>;if(page==="users")return <Basic title="المستخدمون" icon="♟"/>;if(page==="requests")return <Basic title="طلبات التقديم" icon="✓"/>;if(page==="reports")return <Basic title="التقارير" icon="▥"/>;if(page==="assistants")return <Basic title="المساعدون والصلاحيات" icon="◇"/>;if(page==="audit")return <Basic title="سجل العمليات" icon="◌"/>;if(page==="backup")return <Backup/>;if(page==="system")return <Basic title="حالة النظام" icon="▦"/>;if(page==="profile")return <Profile user={user}/>;return <Basic title={page==="notifications"?"الإشعارات":page==="rules"?"القوانين والتوجيهات":"الإعدادات"} icon={page==="notifications"?"◉":page==="rules"?"▤":"⚙"}/> }
function Title({t,d,i}){return <div className="title"><b>{i}</b><div><h2>{t}</h2><p>{d}</p></div></div>}
function Home({role,user,setPage}){let owner=role==="OWNER"||role==="OWNER_ASSISTANT";let cards=owner?[["إجمالي المستخدمين","1,248","+8.4%"],["الطلبات الجديدة","26","تحتاج مراجعة"],["الشكاوى المفتوحة","14","3 عاجلة"],["تمويل الوسطاء","18.4M","د.ع هذا الشهر"]]:role==="BROKER"?[["سعر الرفعة","750,000","د.ع"],["المدفوع","500,000","د.ع"],["المتبقي","250,000","د.ع"],["التمويل الشهري","750,000","د.ع"]]:[["حالة الحساب",user.is_verified?"مقبول":"عضو",user.is_verified?"تم التحقق":"لا يوجد طلب نشط"],["الإشعارات","03","غير مقروءة"],["القوانين","05","تحديثات جديدة"],["الدعم","24/7","تواصل معنا"]];return <div className="page"><section className="hero"><small>DASHBOARD • {meta[role]?.[0]}</small><h2>{owner?"مركز قيادة Super Amazon":role==="BROKER"?"لوحتك المالية والإدارية":"كل ما تحتاجه في مكان واحد"}</h2><p>{owner?"راقب المنصة وراجع الطلبات وأدر المستخدمين من لوحة واحدة.":"واجهة مخصصة حسب نوع حسابك."}</p></section><div className="stats">{cards.map(c=><div className="stat"><small>{c[0]}</small><strong>{c[1]}</strong><span>{c[2]}</span></div>)}</div><h3>الوصول السريع</h3><div className="quick">{(owner?[["الطلبات","راجع الطلبات","requests"],["الشكاوى","إدارة الشكاوى","complaints"]]:role==="MEMBER"? [["تقديم شكوى","اختر ADMIN أو BROKER","complaints"]]:role==="BROKER"? [["المالية","الرفعات والتمويل","finance"]]:[["حالة الطلب","تابع طلبك","application"]]).map(x=><button onClick={()=>setPage(x[2])}><b>{x[0]}</b><small>{x[1]}</small><i>←</i></button>)}</div></div>}
function Complaints(){return <div className="page"><Title t="الشكاوى" d="قدم شكوى بطريقة واضحة وتابع حالتها." i="⚑"/><div className="cols"><section className="panel"><h3>تقديم شكوى جديدة</h3><label>القسم</label><div className="seg"><button>ADMIN</button><button className="on">BROKER</button></div><label>اختر الشخص</label><select><option>قائمة الأشخاص ستظهر هنا بعد الربط بالـ API</option></select><label>تفاصيل الشكوى</label><textarea rows="7" placeholder="اكتب تفاصيل الشكوى هنا..."></textarea><div className="upload">＋ أرفق صورًا أو فيديو أو مستندات</div><button className="primary">إرسال الشكوى</button></section><section className="panel"><h3>مراحل الشكوى</h3><p>① جديدة</p><p>② قيد المراجعة</p><p>③ تمت المعالجة</p><p>④ مغلقة</p></section></div></div>}
function Finance(){return <div className="page"><Title t="المالية" d="عرض وضعك المالي بشكل واضح." i="₿"/><section className="finance"><small>المتبقي</small><strong>250,000 د.ع</strong><span>من إجمالي 750,000 د.ع</span><div><i/></div></section><div className="stats"><div className="stat"><small>سعر الرفعة</small><strong>750,000</strong><span>د.ع</span></div><div className="stat"><small>المدفوع</small><strong>500,000</strong><span>د.ع</span></div><div className="stat"><small>التمويل الشهري</small><strong>750,000</strong><span>د.ع</span></div></div><section className="panel"><h3>آخر الدفعات</h3><Table rows={[["#PAY-120","رفعة","500,000","18/08/2026"],["#PAY-098","تمويل","750,000","01/08/2026"]]}/></section></div>}
function Backup(){return <div className="page"><Title t="النسخ الاحتياطي" d="مركز النسخ الاحتياطي اليومي إلى Telegram." i="↻"/><section className="backup"><h3>✓ آخر نسخة ناجحة</h3><strong>اليوم • 03:00</strong><p>النسخة سليمة ومشفرة</p><div className="stats"><div><small>الحجم</small><b>184 MB</b></div><div><small>SHA-256</small><b>••••••••</b></div><div><small>القناة</small><b>محددة من Owner</b></div></div><button className="primary">إنشاء نسخة اختبارية</button></section></div>}
function Profile({user}){return <div className="page"><Title t="ملفي الشخصي" d="معلومات حسابك الأساسية." i="◎"/><section className="profile"><b>SA</b><div><h2>{user.telegram_name||"المستخدم"}</h2><p>@{user.telegram_username||"غير محدد"}</p><small>Telegram ID: {user.telegram_id}</small></div></section></div>}
function Basic({title,icon}){return <div className="page"><Title t={title} d="هذا القسم مصمم للربط مع خدمات النظام وقاعدة البيانات." i={icon}/><section className="panel"><h3>{title}</h3><Table rows={[["بيانات تجريبية","جاهز للربط","—","—"],["—","—","—","—"]]}/></section></div>}
function Table({rows}){return <div className="table"><div className="tr head"><span>العنصر</span><span>النوع</span><span>التاريخ</span><span>الحالة</span></div>{rows.map(r=><div className="tr">{r.map(x=><span>{x}</span>)}</div>)}</div>}
createRoot(document.getElementById("root")).render(<App/>);
